### ISSUE TITLE
[Question] After Heroku going into the sleep mode, the bot will be no reply? And could not be waked?

### ISSUE THREAD

**Issue by Livan-91** [Quiec/pmChatBot#3]
Don't know if I make Heroku configuration right?

**Comment by yusufusta** [comment]
As far as I know, there is no sleep mode because the worker dyno has been working (not the web).

I used it for a long time, nothing happened.

**Comment by Livan-91** [comment]
It happend once or twice this afternoon, then I restarted all the dynos, and the bot works fine until now, thanks for your reply!
